---
- name: Started and Enabled Chrony
  service: 
    name: chronyd
    enabled: true
    state: started

- name: Restart NTP
  service: 
    name: chronyd
    state: restarted

- name: Restart Firewalld
  service: 
    name: firewalld 
    state: restarted

- name: Started and Enabled Chrony on Debian
  service: 
    name: chrony
    enabled: true
    state: started

- name: Restart Chrony
  service: 
    name: chrony 
    state: restarted

    

    