---
- name: Deploy NTP Server on CentOS
  include_tasks: centos_ntp_server.yaml
  when: 
    - ansible_os_family == "RedHat"

- name: Deploy NTP Server on Debian
  include_tasks: debian_ntp_server.yaml
  when: 
    - ansible_os_family == "Debian"